name=TomatoCube Xmas Lantern
version=1.0
author=TomatoCube
maintainer=TomatoCube <tomato@tomatocube.com>
sentence=Allow kids to check out the code loaded on the CH552 LaserCut Lantern. 
paragraph=Enjoy & Have a Merry Christmas - 2022. 
category=Machine
url=https://github.com/TomatoCube18/ch55xduino
architectures=mcs51
